# Generated by Django 6.0.1 on 2026-02-12 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', help_text='Leave blank to auto-fill from IMDb', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Leave blank to auto-fill from IMDb')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Leave blank to auto-fill from IMDb', null=True)),
                ('video_file', models.FileField(upload_to='media/videos/')),
                ('category', models.CharField(blank=True, default='', help_text='Leave blank to auto-fill from IMDb genre', max_length=100)),
                ('type', models.CharField(blank=True, default='', help_text='movie, series, etc. - auto-filled from IMDb', max_length=50)),
                ('codec', models.CharField(blank=True, default='', max_length=50)),
                ('resolution', models.CharField(blank=True, default='', max_length=20)),
                ('audio_codec', models.CharField(blank=True, default='', max_length=50)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=32, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_transcoded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preview_duration', models.IntegerField(default=120, help_text='Preview duration in seconds')),
                ('start_offset', models.IntegerField(default=0, help_text='Start offset in seconds')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_transcoded', models.BooleanField(default=False)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='video_app.video')),
            ],
            options={
                'verbose_name': 'Preview',
                'verbose_name_plural': 'Previews',
            },
        ),
    ]
